// <auto-generated />
namespace CustomerProfileBank.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initial2562019 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial2562019));
        
        string IMigrationMetadata.Id
        {
            get { return "201906251936186_initial-25-6-2019"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
