// <auto-generated />
namespace CustomerProfileBank.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fbM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fbM));
        
        string IMigrationMetadata.Id
        {
            get { return "201906220846140_fbM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
